name: Build the backend

on:
  push:
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        working-directory: ./backend
    
      - name: Run tests
        run: uv run pytest --cov=src --cov-report=term-missing
        working-directory: ./backend
